version: '3.8'

services:
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl:ro 